#!/bin/env python

##################################################################################################
# Name:        archlogstat                                                                       #
# Author:      Randy Johnson                                                                     #
# Description: Report information on archived redo logs.                                         #
#                                                                                                #
# Usage: archlogstat [options]                                                                   #
#                                                                                                #
# Options:                                                                                       #
#  -h, --help   show this help message and exit                                                  #
#  -c           RMAN> list copy of archivelog ...                                                #
#  -b           RMAN> list backup of archivelog ...                                              #
#  -d           include deleted archivelogs in the report.                                       #
#  -n NAME      where upper(name) like '%sssss%'                                                 #
#  -m MEDIA     RMAN> list backup ... device type disk/sbt (default=ALL                          #
#  -f FIRSTSCN  where first_change# >= nnnnn                                                     #
#  -l LASTSCN   where next_change#  <= nnnnn                                                     #
#  -r           RMAN> list copy/backup of archivelog ...                                         #
#  --s          print SQL query.                                                                 #
#  --v          print version info.                                                              #
#                                                                                                #
# History:                                                                                       #
#                                                                                                #
# Date       Ver. Who              Change Description                                            #
# ---------- ---- ---------------- ------------------------------------------------------------- #
# 09/25/2016 1.00 Randy Johnson    Initial write.                                                #
##################################################################################################

# --------------------------------------
# ---- Import Python Modules -----------
# --------------------------------------
from optparse     import OptionParser
from os           import environ
from os.path      import basename
from sys          import argv
from sys          import exit
from sys          import version_info
from signal       import SIGPIPE
from signal       import SIG_DFL
from signal       import signal
from Oracle       import RunSqlplus
from Oracle       import RunRman
from Oracle       import SetOracleEnv
from Oracle       import ParseConnectString
from Oracle       import PrintError


# --------------------------------------
# ---- Main Program --------------------
# --------------------------------------
if (__name__ == '__main__'):
  Cmd            = basename(argv[0]).split('.')[0]
  CmdDesc        = 'Archivelog Status'
  Version        = '1.00'
  VersionDate    = 'Sun Sep 25 14:04:25 CDT 2016'
  DevState       = 'Production'
  Banner         = CmdDesc + ': Release ' + Version + ' '  + DevState + '. Last updated: ' + VersionDate
  Rcv            = ''
  Sql            = ''
  SqlHeader      = '/***** ' + CmdDesc.upper() + ' *****/'
  ErrChk         = False
  ArgParser      = OptionParser()
  ConnStr        = ''

  # For handling termination in stdout pipe; ex: when you run: oerrdump | head
  signal(SIGPIPE, SIG_DFL)

  ArgParser.add_option('-c',  dest='ListCopy',   action='store_true', default=False,            help="RMAN> list copy of archivelog ...")
  ArgParser.add_option('-b',  dest='ListBackup', action='store_true', default=False,            help="RMAN> list backup of archivelog ...")
  ArgParser.add_option('-d',  dest='Deleted',    action='store_true', default=False,            help="include deleted archivelogs in the report.")
  ArgParser.add_option('-n',  dest='Name',                            default='',    type=str,  help="where upper(name) like '%sssss%'")
  ArgParser.add_option('-m',  dest='Media',                           default='',    type=str,  help="RMAN> list backup ... device type disk/sbt (default=ALL")
  ArgParser.add_option('-f',  dest='FirstScn',                        default='',    type=str,  help="where first_change# >= nnnnn")
  ArgParser.add_option('-l',  dest='LastScn',                         default='',    type=str,  help="where next_change#  <= nnnnn")
  ArgParser.add_option('--s', dest='Show',       action='store_true', default=False,            help="print SQL query.")
  ArgParser.add_option('--v', dest='ShowVer',    action='store_true', default=False,            help="print version info.")

  # Parse command line arguments
  Options, args = ArgParser.parse_args()

  ListCopy   = Options.ListCopy
  ListBackup = Options.ListBackup
  Media      = Options.Media
  Deleted    = Options.Deleted
  Name       = Options.Name
  FirstScn   = Options.FirstScn
  LastScn    = Options.LastScn
  Show       = Options.Show
  ShowVer    = Options.ShowVer
  
  if (ListCopy == True or ListBackup == True):
    Rman = True
  else:
    Rman = False

  #if (ListBackup == False and ListCopy == False):
  #  ListBackup = True
  #  ListCopy   = True
    
  if (Media == ''):
    Media = 'ALL'
  else:
    Media = Media.upper()
    if (Media == 'TAPE'):
      Media = 'SBT'

  if (LastScn != ''):
    LastScn = str(int(LastScn) + 1)

  if (ShowVer == True):
    print('\n%s' % Banner)
    exit()

  if (Name != '' and Rman == True):
    if (FirstScn != '' or LastScn != ''):
      print('Name option (-n) cannot be used with FirstScn (-f) or LastScn (-l) option when searching the backups.')
      exit(1)

  if (Rman == True):
    if ((FirstScn == '' and LastScn != '') or (LastScn == '' and FirstScn != '')):
      print('FirstScn (-f) and LastScn (-l) options must be used together when searching the backups.')
      exit(1)

  if (Rman == True):
    if (ListCopy == True):
      Rcv += "LIST COPY OF ARCHIVELOG"
      if ((FirstScn == '' or LastScn == '') and (Name == '')):
        Rcv += ' ALL'
      else:
        if (FirstScn != ''):
          Rcv += " FROM SCN " + FirstScn
        if (LastScn != ''):
          Rcv += " UNTIL SCN " + LastScn
        if (Name != ''):
          Rcv += " LIKE '%" + Name + "%'"
      Rcv += ";"

  
    if (ListBackup == True):
      if (Media == 'ALL' or Media == 'DISK'): 
        if (ListCopy == True):
          Rcv += "\n"
        Rcv += "LIST BACKUP OF ARCHIVELOG"
        if ((FirstScn == '' or LastScn == '') and (Name == '')):
          Rcv += ' ALL'
        else:
          if (FirstScn != ''):
            Rcv += " FROM SCN " + FirstScn
          if (LastScn != ''):
            Rcv += " UNTIL SCN " + LastScn
          if (Name != ''):
            Rcv += " LIKE '%" + Name + "%'"
        Rcv += " DEVICE TYPE DISK;"
  
      if (Media == 'ALL' or Media == 'SBT'):
        if (ListCopy == True or Media == 'ALL' or Media == 'DISK'):
          Rcv += "\n"
        #if (Media == 'ALL'):
        #  Rcv += "\n"
        Rcv += "LIST BACKUP OF ARCHIVELOG"
        if ((FirstScn == '' or LastScn == '') and (Name == '')):
          Rcv += ' ALL'
        #Rcv += "LIST BACKUP OF ARCHIVELOG"
        if (FirstScn != ''):
          Rcv += " FROM SCN " + FirstScn
        if (LastScn != ''):
          Rcv += " UNTIL SCN " + LastScn
        if (Name != ''):
          Rcv += " LIKE '%" + Name + "%'"
        Rcv += " DEVICE TYPE SBT;"

    if(Show):
      print('-----------cut-----------cut-----------cut-----------cut-----------cut-----------')
      print(Rcv)
      print('-----------cut-----------cut-----------cut-----------cut-----------cut-----------')
      exit()
    
    # Check/setup the Oracle environment
    if (not('ORACLE_SID' in list(environ.keys()))):
      print('ORACLE_SID is required.')
      exit(1)
    else:
      # Set the ORACLE_HOME just in case it isn't set already.
      if (not('ORACLE_HOME' in list(environ.keys()))):
        (OracleSid, OracleHome) = SetOracleEnv(environ['ORACLE_SID'])
    
    # Parse the connect string if any, prompt for username, password if needed.
    if (len(args) > 0 and Show == False):
      InStr = args[0]
      ConnStr = ParseConnectString(InStr)
    
    # Execute the report
    print("\nReport Status of Archivelogs in RMAN:")
    if (ListCopy == True):
      print("  - List Copy of archivelog ...")
    if (ListBackup == True):
      if (Media == 'ALL' or Media         == 'DISK'):
        print("  - List Backup of archivelog device type DISK")
      if (Media == 'ALL' or Media == 'SBT'):
        print("  - List Backup of archivelog device type SBT")

    if (ConnStr != ''):
      (Stdout) = RunRman(Rcv, ErrChk, ConnStr)
    else:
      (Stdout) = RunRman(Rcv, ErrChk)

  else:
    Sql += "column name                  format a80             heading 'Name'\n"
    Sql += "column first_change#         format 999999999999999 heading 'First SCN'\n"
    Sql += "column next_change#          format 999999999999999 heading 'Last SCN'\n"
    Sql += "column sequence#             format 9999999999      heading 'Sequence'\n"
    Sql += "column backup_count          format 999             heading 'Backup Count'\n"
    Sql += "column deleted               format a7              heading 'Deleted'\n"
    Sql += "column is_recovery_dest_file format a8              heading 'FRA File'\n"
    Sql += "\n"
    Sql += "  SELECT " + SqlHeader + "\n"
    Sql += "         name\n"
    Sql += "       , first_change#\n"
    Sql += "       , next_change# - 1 next_change#\n"
    Sql += "       , sequence#\n"
    Sql += "       , backup_count\n"
    Sql += "       , initcap(deleted) deleted\n"
    Sql += "       , initcap(is_recovery_dest_file) is_recovery_dest_file\n"
    Sql += "    FROM v$archived_log\n"
    Sql += "   WHERE 1=1\n"
    if (Deleted != True):
       Sql += "     AND upper(deleted) = 'NO'\n"
    if (FirstScn != ''):
      Sql += "     AND first_change# >= " + FirstScn + "\n"
    if (LastScn != ''):
      Sql += "     AND next_change#  <= " + LastScn + "\n"
    if (Name != ''):
      Sql += "     AND upper(name) LIKE '%" + Name.upper() + "%'\n"
    Sql += "ORDER BY first_change#;"
    
    if(Show):
      print('-----------cut-----------cut-----------cut-----------cut-----------cut-----------')
      print(Sql)
      print('-----------cut-----------cut-----------cut-----------cut-----------cut-----------')
      exit()
    
    # Check/setup the Oracle environment
    if (not('ORACLE_SID' in list(environ.keys()))):
      print('ORACLE_SID is required.')
      exit(1)
    else:
      # Set the ORACLE_HOME just in case it isn't set already.
      if (not('ORACLE_HOME' in list(environ.keys()))):
        (OracleSid, OracleHome) = SetOracleEnv(environ['ORACLE_SID'])
    
    # Parse the connect string if any, prompt for username, password if needed.
    if (len(args) > 0 and Show == False):
      InStr = args[0]
      ConnStr = ParseConnectString(InStr)
    
    # Execute the report
    print("\nReport Status of Archivelogs in V$ARCHIVED_LOG:")
    if (ConnStr != ''):
      (Stdout) = RunSqlplus(Sql, ErrChk, ConnStr)
    else:
      (Stdout) = RunSqlplus(Sql, ErrChk)

  # Print the report
  if (Stdout != ''):
    print('\n%s' % Stdout)

  exit(0)
# --------------------------------------
# ---- End Main Program ----------------
# --------------------------------------
