#!/bin/bash

ps -ef | grep pmon | grep -v grep | grep -v perl | grep -v ASM | grep -v DBFS |\
while read PMON; do
   INST=`echo "$PMON" | awk {' print $8 '} | cut -f3 -d_`
  echo $INST

  MAIN_ENV=~/.env/main.env
  if [ -r $MAIN_ENV ]; then
     . $MAIN_ENV $INST
  else
     echo 'Could not open $MAIN_ENV for read.'
  fi

  PFILE=/tmp/init${ORACLE_SID}.ora.backup
  
  echo
  echo Dumping database spfile to $PFILE

  sqlplus -s /nolog <<-EOF
  connect / as sysdba
  create pfile='$PFILE' from spfile;
EOF

done

